###

GET http://localhost:4004/odata/v4/catalog/OrderHistory?$filter=shipTo eq '12345678' 


###
GET http://localhost:4004/odata/v4/catalog/OrderHistory?$filter=shipTo eq '12345678' and hybrisOrderNumber eq 'G1234567' and orderStatus eq ['1','2']


####

GET  http://localhost:4004/odata/v4/catalog/OrderHistory


###
GET http://localhost:4004/odata/v4/catalog/OrderHistory?soldTo=203800&fromDate=2021-03-10T00:00Z&toDate=2021-12-31T23:59:59Z&status=1,2&sort=orderDate&dir=desc&currentPage=0&pageSize=12&orderType=PO,SO


###
GET http://localhost:4004/odata/v4/erp-order-history/Payload
Content-Type: application/json

{
    "soldTo": "23423423",
    "search": "",
    "searchBy": "",
    "fromDate": "2021-03-10T00:00Z",
    "toDate": "2021-12-31T23:59:59Z",
    "status": "1",
    "sort": "orderDate",
    "dir": "desc",
    "currentPage": "0",
    "pageSize": "12",
    "orderType1": "PO"
}

###

POST http://localhost:4004/odata/v4/erp-order-history/Payload
Content-Type: application/json

{
"soldTo": "3783115",
"search": "",
"searchBy": "",
"fromDate": "2021-03-10T00:00Z",
"toDate": "2021-12-31T23:59:59Z",
"status": ["1","2"],
"sort": "orderDate",
"dir": "desc",
"currentPage": 0,
"pageSize": 12,
"orderType": ["PO","SO"]
}

# {
#   "shipTo": "34567890",
#       "hybrisOrderNumber": "H1234567",
#       "erpOrderNumber": "34567890",
#       "poNumber": "SO3456789",
#       "paymentTerms": "Cost Center",
#       "orderType": "SO",
#       "orderPlacedBy": "Kenrick",
#       "currency": "EUR",
#       "totalPrice": 2020,
#       "erpOrderType": "SW",
#       "orderStatus": "1",
#       "orderDate": "2020-05-01T00:00:00.001Z"
# }


###

GET http://localhost:4004/odata/v4/catalog/OrderHistory?$filter=shipTo eq '12345678' and hybrisOrderNumber eq 'G1234567' and (orderStatus eq '1' or orderStatus eq '2') and (orderType eq 'PO' or orderType eq 'SO')&$orderby=erpOrderNumber desc

# GET http://localhost:4004/odata/v4/catalog/OrderHistory?$filter=(orderStatus eq '1' or orderStatus eq '2')&$orderby=orderDate desc


###
GET  https://a18ce1dftrial-dev-snah-orderhistory-srv.cfapps.us10-001.hana.ondemand.com/odata/v4/catalog/OrderHistory